### ISSUE TITLE
Tab view is visible in popup windows

### ISSUE THREAD

**Issue by theamazing0** [ranmaru22/firefox-vertical-tabs#100]
The tab view is visible in popup windows (such as Sign in with Google popups).
![2023-04-23T17:32:20,127356438-04:00](https://user-images.githubusercontent.com/66532288/233867355-6921789e-914c-4729-80ea-6a60d60b2ec0.png)

**Comment by JokeDeity** [comment]
Also looking for a change for this as I keep having it on download popup windows and it's annoying.
