### ISSUE TITLE
Wrong GTK colors in the header bar

### ISSUE THREAD

**Issue by abUwUser** [ranmaru22/firefox-vertical-tabs#101]
The header bar colors are applied wrongly and does not represent the correct color scheme that should be applied. They differ from other GTK applications, and even from other themes that applies the color correctly (e.g. Firefox Onebar)
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/27961224/acc32b1e-a5aa-4972-b49e-5b5ad2be23f8)
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/27961224/62600e4b-8925-4587-bfc1-e98f1f1d508d)
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/27961224/33152489-9728-43a8-b5ca-430b721eb585)

**Comment by abUwUser** [comment]
might gonna check that. but why was that line added just to know

**Comment by abUwUser** [comment]
Interesting. Looks like that color is only used on windows 10
![Screenshot from 2023-05-25 20-06-40](https://github.com/ranmaru22/firefox-vertical-tabs/assets/27961224/b91049a7-8ddd-41ac-9da8-61ff02a39df9)

**Comment by abUwUser** [comment]
Removing them doesn't seem to work tho :P

**Comment by abUwUser** [comment]
After doing some studying, apparently Firefox adds the wrong colors to `--toolbar-bgcolor` and as such we get those colors. I still have to study if that affects adwaita themes with the coloring that I added with Gracience. For now, this code should work:
```css
.browser-toolbar:not(.titlebar-color){
    background-color: transparent !important;
    box-shadow: none !important;
}
```

**Comment by abUwUser** [comment]
> I still have to study if that affects adwaita themes with the coloring that I added with Gracience

It does. I am going to create a PR to fix it
![Pasted image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/27961224/2f30915a-4bb9-4faa-9860-a695341e94a5)

**Comment by ranmaru22** [comment]
Thanks, I've merged it. :)
