### ISSUE TITLE
Why not just used a fixed width in pixels for the sidebar? 

### ISSUE THREAD

**Issue by Freeplayg** [ranmaru22/firefox-vertical-tabs#11]
Sometimes the sidebar is just way too thin with the default values.
![2021-07-21_19-02](https://user-images.githubusercontent.com/40742947/126570726-4e406aff-33e0-4108-8a91-6b196cbd90c1.png)

**Comment by ranmaru22** [comment]
I'm currently testing different widths and how they look in small and big windows. I think I will go with a min-width and max-width solution but haven't decided on the exact values yet. Still playing around.

**Comment by ranmaru22** [comment]
I have changed this now to a max-width of 200px and 250px for viewports >= 1200px. This means the sidebar will try to occupy 30vw of the screen's width but cap at those values if it would become larger.

On very small screens this can mean that the expanded sidebar could cover a majority of the window, but I think that's better than not having any expansion at all.
