### ISSUE TITLE
CSS exceeds storage quota for webextensions if not minified

### ISSUE THREAD

**Issue by RobinBoers** [ranmaru22/firefox-vertical-tabs#116]
Hi! I tried to reinstall this on a new computer after I used it on an old PC. I followed the exact instructions of the README, but the custom CSS was not saving. I opened the extension debugger and saw this:

![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/60298132/c183e841-3bba-4369-baa0-89c5d153948e)

Turns out there's a max size for the custom CSS. Minifying it fixed it.

Maybe minified should be the default? I'm happy to open a PR to minify the file and add a note to the README.

Cheers!

**Comment by ranmaru22** [comment]
#123 adds minified files to every release via a GH action.
