### ISSUE TITLE
Change the default bg color

### ISSUE THREAD

**Issue by Minnona** [ranmaru22/firefox-vertical-tabs#125]
Hey, how do I change it? Couldn't find anything containing rgb(255, 255, 255) in the code. Wanted to change it to FF's default rgb(204, 204, 204) for these side menus.
Cheers!

**Comment by ranmaru22** [comment]
That's something Tab Center Reborn controls.

Just add `background-color: rgb(204, 204, 204);` to the `body` selector inside the extension's custom stylesheet (around line 34 in `tabCenterReborn.css`). That should do the trick.

**Comment by Minnona** [comment]
It worked, thanks!
