### ISSUE TITLE
"Save CSS" isn't working...

### ISSUE THREAD

**Issue by ElwannGuillemot** [ranmaru22/firefox-vertical-tabs#128]
I don't understand, I'm copy/pasting the content of "tabCenterReborn.css" in the Tab Center Reborn's custom stylesheet, then click on "save CSS" and nothing happens. And if I restart firefox, the custom CSS didn't get saved.
I may just be dumb but help me plss

**Comment by GanterFengDavid** [comment]
I have the same problem, and it turns out that `tabCenterReborn.css` does not save, but `tabCenterReborn.min.css` works well.

You can download `tabCenterReborn.min.css` at https://github.com/ranmaru22/firefox-vertical-tabs/releases/tag/v6.0

**Comment by ranmaru22** [comment]
Yes, this is unfortunately a side-effect of this mod growing too large. The CSS is too long in its non-minified form and Firefox won't accept it. Your options are to either use the minified version as GanterFengDavid suggested, or to remove some of the optional code from the file until it works.

There's nothing we can do about this, it's a limitation from how Firefox handles extensions.
