### ISSUE TITLE
Improvement: A separator between pinned tabs and normal tabs

### ISSUE THREAD

**Issue by cescur** [ranmaru22/firefox-vertical-tabs#129]
Hi!
This is working flawlessly in my setup (Win 11 64bits, FF 117), thank you very much!

I kindly ask for an improvement: A separator, as with different background colors or with a line between pinned and normal tabs. That's it. I think it would be super useful to have it added to the addon. Thanks again :)

**Comment by ranmaru22** [comment]
I think I can add something like this. I'll put it on the list for the next update. ;)

**Comment by elvinvandalen** [comment]
I am trying to remove this separator, but I'm struggling to find this in the css. Any idea where to find this?

**Comment by ranmaru22** [comment]
See https://github.com/ranmaru22/firefox-vertical-tabs/pull/142/files

The line with `#pinnedtablist`.
