### ISSUE TITLE
Moving the vertical tabs to the right creates a "buffer" space on the right

### ISSUE THREAD

**Issue by gksjohn** [ranmaru22/firefox-vertical-tabs#130]
After changing ```-positionX2: absolute``` in UserChrome.css, a buffer area that shows nothing on the right is created upon moving the sidebar to the right. Is there any way to correct this in CSS?

It seems the space allocated for the vertical tabs on the left side is just empty (without the tabs of course)

**Comment by YAEGGER** [comment]
same here, any solutions?

**Comment by gksjohn** [comment]
> same here, any solutions?

https://www.reddit.com/r/FirefoxCSS/comments/16hijr4/how_to_remove_spacer_on_right_side_of_browser/

This seems to have fixed a user's issues. I've just used another person's version of vertical tabs.
