### ISSUE TITLE
Tab sidebar does not appear when pulling a tab into its own window

### ISSUE THREAD

**Issue by jaredtapiakt** [ranmaru22/firefox-vertical-tabs#132]
The tab sidebar does not appear when clicking and dragging a tab from one window into open space (i.e. moving that tab into a new window). This new window simply shows the webpage and the standard address bar, but no tabs of any sort are visible. I also cannot click and drag other tabs into this new window. I _can_ create new tabs using ctrl+t, but the only way to traverse those tabs in that new window is to ctrl[+shift]+tab.

**Comment by ranmaru22** [comment]
This is not an issue with this mod, but how Firefox behaves upon creating new frames. The sidebar is disabled by default and you need to open it, either by shortcut or by putting the sidebar toggle into the menu bar and clicking that. 

However, if you open a new window, toggle the sidebar on, and then close it, Firefox _should_ remember that and open it when creating a new frame. If it does not, this seems to be an issue on your end where your Firefox isn't saving the default frame parameters. 

See also: https://support.mozilla.org/en-US/questions/1342740
