### ISSUE TITLE
Visual bugs with Firefox 119 Beta on Windows 11

### ISSUE THREAD

**Issue by diabeetus01** [ranmaru22/firefox-vertical-tabs#135]
Hello!

I've been using this for a while and it's an absolutely wonderful project, makes browsing with Firefox so much nicer, but my machine just updated to Firefox 119 Beta and I am now having some UI bugs. Namely the Forward/Back buttons are missing from the Toolbar, and the window close/maximize/minimize buttons have turned white.
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/7763023/e1947cdb-4a1f-4242-892d-9ee958b6a6c2)

I am using the default theme and made sure to remove any other .css customizations prior to make sure what was causing this, and it's pointed back to this .css. I also reset my toolbar customizations to be sure as well.
Just wanted to put this on your radar, thank you!

**Comment by ranmaru22** [comment]
Thank you. This does not seem to occur on macOS or Linux. I'll put a help wanted tag on this b/c I don't have a Windows machine to reproduce this on. 

PRs welcome.

**Comment by diabeetus01** [comment]
Was messing around with the userChrome.css settings for the Windows UI, and then tried just changing my theme and re-applying the default light/dark theme and this seems to have fixed the UI elements.
Seems to be some strange bug when going from 118 to 119, but a re-apply of the theme sorted it here.

**Comment by masonbesmer** [comment]
@diabeetus01 build 119 20231019122658, experiencing same issue. What did you do to fix it?

**Comment by masonbesmer** [comment]
Was able to fix it by changing the theme but going back to the automatic theme breaks it again.

But now, the tab bar covers my bookmark bar on my new tab page:
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/16657872/d111b865-871c-48bd-bcc6-c8a02afdc87a)

**Comment by 1human** [comment]
> Was able to fix it by changing the theme but going back to the automatic theme breaks it again.
> 
> But now, the tab bar covers my bookmark bar on my new tab page: ![image](https://user-images.githubusercontent.com/16657872/278773029-d111b865-871c-48bd-bcc6-c8a02afdc87a.png)

Hello！Can you share the css file you used?
The open new pages button is at the top of  vertical tabs...
![图片](https://github.com/ranmaru22/firefox-vertical-tabs/assets/18576031/59269d44-b441-4c0b-863a-249eece0be19)

**Comment by masonbesmer** [comment]
Hey there, I'm using the userChrome.css and minified css from this repo. I also tried the non-minified and no change. The issue only occurs on new tabs.

**Comment by Suhaybu** [comment]
I also have this issue but only in incognito windows. However, I was able to fix it by changing my theme from Auto(Dark/Light) to Dark. Not sure why that worked, but make sure to not use the Auto theme.

**Comment by LP0101** [comment]
Same issue here on 119.0.1 on Windows 11.  I tried switching between Auto and Dark, no success.
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/16864921/68567704-da09-4021-b9f4-f66e393ccf93)

**Comment by Dekamir** [comment]
For those still having the white window controls, you need to choose the Dark theme from **Themes** (in `about:addons`), and not Settings.
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/28929300/73c738b1-5210-4b87-98af-2d307ae48707)

**Comment by RavenStryker** [comment]
> For those still having the white window controls, you need to choose the Dark theme from **Themes** (in `about:addons`), and not Settings. ![image](https://user-images.githubusercontent.com/28929300/282266912-73c738b1-5210-4b87-98af-2d307ae48707.png)

This fixed the issue I had withy my custom fork alongside with using the below code. Back in action!
/* Windows specific styles */
@media (-moz-platform: windows),
       (-moz-platform: windows-win10) {
