### ISSUE TITLE
Can this be configured to not have auto side of the sidebar

### ISSUE THREAD

**Issue by mukulsharma9118** [ranmaru22/firefox-vertical-tabs#136]
Hey I use edge for work and firefox for personal browsing, in order to not have context switch can we make the sidebar static as well 
<img width="416" alt="image" src="https://github.com/ranmaru22/firefox-vertical-tabs/assets/21037912/1b555b01-f0d7-49a1-968c-36822928198c">

**Comment by ranmaru22** [comment]
Sure, you can do that. Just copy everything from the hover classes in both files to the normal sidebar classes (esp. the width info) and delete the hover classes.

That would make it always expanded.

**Comment by elektrinis** [comment]
I want this as well. Instructions not clear, as there are many "hover"s.
Can we have a separate version or a simple on/off?
I just want what edge has by default, including tab grouping.

**Comment by ranmaru22** [comment]
No, I will not introduce more complexity into this project by allowing options. We are currently scratching the level that's possible to the point where you have to run a minified version of the CSS unless you want Firefox to flip out about the payload size. More options means we'd be blowing this up even more, making it even more complicated for the average user to use by either providing multiple files you'd have to mix and match or by telling them to delete lines to make it run or run a minifyer themselves. 

Neither of that is a good solution. 

This was always supposed to be a "plug and play" type of thing that you could load into your Firefox and be good to go. We've reached a point where this is already not the case anymore (just look at the instructions in the README) and I won't blow this up anymore. We already have issues almost every time a new version of Firefox releases, and more conditions would make this worse. 

Feel free to fork the project though, or make any changes you like. You can just play around with the CSS yourself and see the changes live in Firefox (if you're not using the minified version, that is, which is another case against it). 

As for which hover classes you need to remove to achieve this: all of them. If your goal is to have it always expanded, there will be no hover functionality whatsoever, so they all need to go.
