### ISSUE TITLE
Feature: Unload all tab except the current one 

### ISSUE THREAD

**Issue by dmitrykulakovfrontend** [ranmaru22/firefox-vertical-tabs#139]
Hey! This is amazing extension and thank you so much for creating and maintaining it!

My problem is that very often I'm ending up with a lot of tabs loaded, which are eating my memory very fast, but then I don't need those tabs to be loaded so I manually unload every one of them to save memory.

If it is possible I would like to ask for a feature to be able unload all tabs except the one I clicked on, like Close other tabs works. That would make my life so much easier, thanks again :)

**Comment by ranmaru22** [comment]
Hey, this would be a functionality that the extension which powers this mod's backend, [Tab Center Reborn](https://framagit.org/ariasuni/tabcenter-reborn), would have to implement. What we're doing here is basically providing a reskin to that.

You might have luck making a feature request there. ;)
