### ISSUE TITLE
Suggestion / request : Integrate Simple Tab Groups

### ISSUE THREAD

**Issue by RBG74** [ranmaru22/firefox-vertical-tabs#140]
Hello, 
I just started using your styling and I'm enjoying it.
I feel like an integration of [Simple Tab Groups](https://addons.mozilla.org/en-GB/firefox/addon/simple-tab-groups/) or a similar extension that adds tab groups or even folders like Sidebery if well integrated into the sidebar would make this the ultimate way to use firefox.
Keep up the great work !

**Comment by ranmaru22** [comment]
I looked into this and I don't think it's possible to extend the support for this any more than it does right now. You can move tab's between groups from the sidebar via the right click menu, and to switch groups you'd need to add the toolbar button.

Any deeper integration would need to come from Tab Center Reborn itself. But is out of scope for a CSS mod like this.
