### ISSUE TITLE
Add license and credit in css files?

### ISSUE THREAD

**Issue by ispanos** [ranmaru22/firefox-vertical-tabs#148]
Hello,

I would like to add your css files in my dotfiles repo and I want to make sure I'm giving your proper credit. [Here](https://github.com/ispanos/dotfiles/tree/master/.config/firefox)'s where I save my firefox config. I use it as a bare repo, so I don't want to add a readme file, as it would appear in my home directory too. I have a "notes.txt" with a link to your repo in the firefox directory, but is there something else I could do?

I have been using vertical tabs for a while now and it was something I always wanted to have. Thank you for making this. Whoever (windows users mostly) sees my set-up is more impressed by firefox, rather than seeing gnome for the first time.

I also have an unrelated question; I'm only adding that here in case it's something easy to answer, otherwise please ignore it.
All other dotfiles in my repo are placed exactly where they need to be after [git clone](https://www.atlassian.com/git/tutorials/dotfiles). Firefox is the only application that I haven't found a way to do that because of the profiles. It is especially annoying (for me) to have to copy-paste the custom style-sheet. Is there a way I can just save the minified style-sheet somewhere instead of going into the extension settings? It would help with syncing across multiple systems using the git repo.

Thank you.

**Comment by ranmaru22** [comment]
Hey. As for the license, the code is licensed under GPL3, so any compatible license would work. As long as you're not slapping a proprietary license on your dotfiles, you're good. 

You're not really redistributing the code anyway, I think dotfiles in general would fall under fair use anyway, but I'm not a lawyer. So I think backlinking is fine. 

As for the other question, no, there unfortunately isn't an easy way to do this. The userChrome file can be symlinked from the repo into the profile directory (which is what I do), but the extension file needs to be copy pasted in, as far as I know.

**Comment by ispanos** [comment]
Thank you!
