### ISSUE TITLE
Collapsed tabs are too big.

### ISSUE THREAD

**Issue by ErnestasMage** [ranmaru22/firefox-vertical-tabs#149]
![Screenshot 2023-12-04 203955](https://github.com/ranmaru22/firefox-vertical-tabs/assets/68244097/f1a8f17f-ed05-4c33-b3f4-81c54e0288fc)
The showcase shows square collapsed tabs, but when I installed the tabs were much higher than intended. Is there any way I could fix it?

**Comment by ranmaru22** [comment]
You need to enable Compact Mode in TCR. Without it, it adds thumbnails to the tabs which results in the bigger size. 

This is described in the Readme.

**Comment by ErnestasMage** [comment]
Thank you.
