### ISSUE TITLE
close minimize and maximize button disappear with userChrome.css on version 123.0a1

### ISSUE THREAD

**Issue by spupuz** [ranmaru22/firefox-vertical-tabs#150]
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/1721792/1944146e-2030-478c-a5e2-207093afdfbc)

as you cab see from the picture no buttons on right uppter side, disabling userChrome.css it appear.

i'm using this version of nightly

![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/1721792/0bc0af99-667c-4b6e-b6e3-fab797575d37)

**Comment by ranmaru22** [comment]
Nightly isn't and never will be officially supported. If this still persists when that version enters the stable channel, report again.
