### ISSUE TITLE
Tab_Center_Reborn css broken?

### ISSUE THREAD

**Issue by Clutchnp** [ranmaru22/firefox-vertical-tabs#157]
![image](https://github.com/ranmaru22/firefox-vertical-tabs/assets/105556048/6f460003-6641-4876-b90a-1b4292c2ba73)
this appears on every private window and disappears when shift+f1 is pressed.
Steps to Reproduce:
1. Download the Release package 
2.Copy the min userchrome.css to -----.default folder 
3.copy the tab reborn min css to custom css in addon preference window

This issue does not happen in non private window

**Comment by ranmaru22** [comment]
Yep, I can reproduce this. Thanks for the report.

123 seems to be breaking quite a lot of things. 😮‍💨

**Comment by ranmaru22** [comment]
Yup, I think I got it. Let me know if v6.3 fixes it for you.

**Comment by Clutchnp** [comment]
Yup that v6.3 fixes it for me.Thanks for the hard work
