### ISSUE TITLE
Can't click close button

### ISSUE THREAD

**Issue by ahal** [ranmaru22/firefox-vertical-tabs#160]
On Fedora 39 with Wayland and Firefox Nightly 124 . When the `userChrome.css` file is present the close button in the top right is not clickable, nor does hovering over it display the red highlight. Normal behaviour returns after removing the `userChrome.css`. Can still close via menu or Alt-F4

This is using this commit:
https://github.com/ranmaru22/firefox-vertical-tabs/commit/9a942d435deb42ec9042c458de99db566e4ad147

**Comment by ranmaru22** [comment]
Nightly is unsupported. Please report back if this persists into beta or dev channels.
