### ISSUE TITLE
back and forward overlaps with window control buttons

### ISSUE THREAD

**Issue by martinericksonn** [ranmaru22/firefox-vertical-tabs#19]
![image](https://user-images.githubusercontent.com/53499729/154894334-7e628035-65a6-4e0c-b0bd-18d51c188e88.png)

The buttons overlap the control bar on my firefox after following the instructions.

**Comment by mustafatutus** [comment]
Hello My Friend.
i had this problem too.  I observed the changes by changing values in "userChrome.css" file and i finally found it.
Go to about:profiles in your URL bar, click /”Open Directory”/ next to your Root Directory under your default profile.
Go to "chrome" named folder and open "userChrome.css"
Values found on lines 26 and 27.
" top: 12px;
  left: 0px; "
and change values
   top: 5px;
   left: 1630px;
save and restart browser.
incompatibility occurs, you can adjust by changing the values.

**Comment by ranmaru22** [comment]
Could you check if #21 fixed this issue? Since your screenshot seems to be on Windows and I can't reproduce this on Mac or Linux, it might be related to that. Thanks. :)
