### ISSUE TITLE
Ctrl+B makes bookmark sidebar replace tabs

### ISSUE THREAD

**Issue by Munzu** [ranmaru22/firefox-vertical-tabs#2]
Windows 10, latest Firefox (v89.0.2)

Steps to replicate:
1. Press Ctrl+B 
    * Bookmark toolbar should now replace the vertical tabs
2. Press Ctrl+B again
    * Bookmark toolbar and vertical tabs disappear
3. Restart Firefox to get tabs back

**Comment by ranmaru22** [comment]
You can get the tabs back by pressing Shift+F1 (that's a Tab Center Reborn shortcut) without restarting.

Hiding the sidebar header  unfortunately also removes the ability to quick switch between it. I haven't found a good solution around this, but you can toggle between the different sidebars by using their keyboard shortcuts.

**Comment by Freeplayg** [comment]
Why not keep the sidebar header? Or move it to the bottom where it's more out of the way

**Comment by ranmaru22** [comment]
I hid it because it looks weird when the sidebar is collapsed (you get a cut-off header that just looks off). 

I guess I could try collapsing it to some minimal form as well, I haven't played much with that idea, but I'll keep it in mind for a future version.

**Comment by ranmaru22** [comment]
This should now be fixed with #10.
