### ISSUE TITLE
FireFox Developer Edition ver.99.0b1 action button moved to leftside

### ISSUE THREAD

**Issue by zhenchai00** [ranmaru22/firefox-vertical-tabs#20]
FireFox Developer Edition did updated to version 99.0b1, the action button for the close, minimize and maximize have pop up to new class `<vbox id="titlebar">`  above the `<toolbar id="nav-bar" class="browser-toolbar">`

If there have people have some clue with this, may share it to me, it will be very appreciated :) 

Following is the reference from my machine:

![firefoxcssbug](https://user-images.githubusercontent.com/76050421/157573106-f6c4f258-7cfa-4ee4-b868-e2a05386c498.gif)

![image](https://user-images.githubusercontent.com/76050421/157573126-d74facd6-4c29-468c-9344-19adf159497b.png)

**Comment by ranmaru22** [comment]
Thanks for the report. This seems to be a Windows-only issue as I can't reproduce it on either Linux or MacOS.

Since I don't have access to a Windows machine I can't easily fix this, but if anyone has a fix, please send a PR and I'll merge it in.

**Comment by zhenchai00** [comment]
Hi @ranmaru22 , I have found the solution to make it from [reddit](https://www.reddit.com/r/FirefoxCSS/comments/tanub7/firefox_developer_edition_ver_990b1_move_action/), I did tried on my local windows machine it was fixed but when I tried to push my fixed branch to your repo, it show some permission denial error to commit something on your repo

Here is the fix:
[line 58](https://github.com/ranmaru22/firefox-vertical-tabs/blob/main/userChrome.css#L58) replace `-moz-os-version` to `-moz-platform` or may refer [here](https://github.com/zhenchai00/dotfiles/blob/main/firefox-vertical-tabs/userChrome.css) #

**Comment by ranmaru22** [comment]
Thanks, I put that in and also put a paragraph about this into the Readme for reference if anyone runs this on older FF versions that might not work with this change.

Compatibility is therefore now v99+.
