### ISSUE TITLE
Windows control buttons in a weird position.

### ISSUE THREAD

**Issue by DeckerExpert** [ranmaru22/firefox-vertical-tabs#24]
~~Hey so the Windows control buttons (Close, Minimize, Maximize) is not looking too well over here. It looks like the buttons are supposed to go next to the back and forward buttons but I'm not too sure.~~
![2022-03-31 12_28_12-About Profiles — Mozilla Firefox](https://user-images.githubusercontent.com/76219178/160983455-c19637a2-dfe6-4c59-88c2-f43ac0abee2c.png)

~~I also have this CSS modification to make the control buttons look like those on Mac, but even those are also broken.~~
![2022-03-31 12_29_13-Issues · ranmaru22_firefox-vertical-tabs — Mozilla Firefox](https://user-images.githubusercontent.com/76219178/160983624-06c04c49-291e-4091-b8b9-11d7e3341cd8.png)

Nevermind, I figured how to fix the above. 

Also is there any way to move the vertical tabs to the right instead?

**Comment by ranmaru22** [comment]
I don't think you can do that by using pure CSS as the sidebar position is rendered by Firefox itself. There might be an extension for it.
