### ISSUE TITLE
Close/minimize buttons moved to the left and overlap with back/forward/refresh

### ISSUE THREAD

**Issue by ghost** [ranmaru22/firefox-vertical-tabs#25]
![Unsaved Image 1](https://user-images.githubusercontent.com/61179434/162197540-6cd4df15-8719-4c39-b09b-cd56dfdffdbf.png)
Only the close button is visible. When I hover to the left of it, "minimize" text box appears too.
Using Pop!_OS 21.10.

**Comment by ranmaru22** [comment]
Ah yes, the Linux settings assume that you use a title bar with the buttons and doesn't reserve space for them like the macOS settings do. 

You can fix this by applying a margin just like in the macOS settings. 

I could make this setting permanent for Linux too but it would create a gap there for people who don't use integrated buttons or use a WM that doesn't have window decorations at all.

**Comment by meff13** [comment]
> Ah yes, the Linux settings assume that you use a title bar with the buttons and doesn't reserve space for them like the macOS settings do.
> 
> You can fix this by applying a margin just like in the macOS settings.
> 
> I could make this setting permanent for Linux too but it would create a gap there for people who don't use integrated buttons or use a WM that doesn't have window decorations at all.

Thanks for responding! I'm new to CSS mods (and Linux in general) and just wanted something looking as close to Edge on Linux without using Edge.
If possible, I think having the margin setting as an optional codeblock in the CSS would be super helpful for beginners, a lot of which probably use DE with integrated buttons on the right.

**Comment by jpkhawam** [comment]
What am I supposed to apply the margin to? I'm not very good with CSS. And if there is a way to have the titlebar buttons on the right again please let me know

**Comment by ranmaru22** [comment]
Sorry for the late reply, this is the part that does this:

```css
#nav-bar {
    padding-left: 80px;
}
```

It's currently only applied on macOS and Linux when `-moz-gtk-csd-available`, which works only with GTK+. You can move that part from the `/* Linux & macOS specific styles */` section into the `/* General styles */` section further down in the userChrome.css file to have it apply unconditionally.

You can also tweak the 80px to reserve more or less space, depending on your buttons style.

**Comment by tplessas** [comment]
What worked for me (GNOME 42.1) was basically removing the `#nav-bar` selector from the `z-index: 100;` rule. Relevant rules look like this:

```
#toolbar-menubar {
    padding-top: 0px !important;
}

#nav-bar {
    padding-right: 80px !important;
}

#TabsToolbar .titlebar-buttonbox-container {
    visibility: visible !important;
    position: absolute;
    top: 8px;
    right: 0px;
}

.titlebar-buttonbox-container {
    display: block;
}
```

and the result looks like this: 
![image](https://user-images.githubusercontent.com/47861171/172735174-d1424556-4b6b-4365-b0db-a6a614b07425.png)

The buttons appear on the right side of the navbar but no icons - will test playing around with `.titlebar-button` sizes.

**Comment by ranmaru22** [comment]
Should be resolved now. Thanks @bmFtZQ!
