### ISSUE TITLE
Button for Temporary Containers

### ISSUE THREAD

**Issue by JJGadgets** [ranmaru22/firefox-vertical-tabs#28]
I use Temporary Containers, and without moving the tab bar to Tab Center Reborn, I have a separate button to open a new tab in a new Temporary Container.

I lose that button using this theme. Could a button be readded in this theme for that? Or would I need to open an issue in upstream Tab Center Reborn?

**Comment by ranmaru22** [comment]
From the top of my head I don't see a way to do this easily with just CSS. Maybe you can move the button over with some positioning magic but that's just guessing. I can try if this is possible but no promises. 

Making a feature request over at TCR would definitely be the cleaner solution.

**Comment by ranmaru22** [comment]
As expected, this isn't possible. The button ins contained in the tab-bar and can't be moved out of it.

You can however right-click on the "New Tab" button in the sidebar and get a list of all your container tabs and then open one from there, if that works for you. For the real deal, this needs to be fixed upstream.

**Comment by JJGadgets** [comment]
> As expected, this isn't possible. The button ins contained in the tab-bar and can't be moved out of it.
> 
> You can however right-click on the "New Tab" button in the sidebar and get a list of all your container tabs and then open one from there, if that works for you. For the real deal, this needs to be fixed upstream.

Will open an issue upstream, thanks for your time.
