### ISSUE TITLE
Inspect element border & responsive menu overlap tabs

### ISSUE THREAD

**Issue by Freeplayg** [ranmaru22/firefox-vertical-tabs#4]
![2021-07-09_21-54](https://user-images.githubusercontent.com/40742947/125148518-d71a3280-e100-11eb-98c7-c659cc8259fd.png)

**Comment by ranmaru22** [comment]
I think this can be fixed by simply adding a z-index prop. I don't get the exact display as shown in your screenshot, but I see this, which is fixed by 6574a13. 

![2021-08-10-19:02:23-scrot](https://user-images.githubusercontent.com/16521734/128902923-ce2ff06a-3599-41bb-b5f1-d505059ca57f.png)
