### ISSUE TITLE
Windows: Uppermost rightmost pixel closes Firefox without this .css, but does not with this .css

### ISSUE THREAD

**Issue by vovavili** [ranmaru22/firefox-vertical-tabs#49]
Hello all!

This is a lovely userchrome.css here, but it has a slight flaw - when you apply it, it adds a degree a precision to closing the browser with your mouse, as you can no longer do it with just by moving your mouse as far up and to the right as possible. This contradicts default behavior in both Edge and stock Firefox.

[Without .css](https://imgur.com/bBrPusj)

[With .css](https://imgur.com/L3dlJZ0)

This should be trivial to amend, I think!

Details:

Firefox version: 103.0.2 (64 bit)

about:config: Only modifications are "browser.compactmode.show - true" and " toolkit.legacyUserProfileCustomizations.stylesheets - true"

Screen size: 1920x1080

Operating system: Windows 11 Pro, 64 bit, version 21H2, OS build 22000.856

userchrome.css : [Basically everything here + some addenda for Tabliss](https://pastebin.com/B4diiQ6g)

Kind regards,
Vladimir

**Comment by vovavili** [comment]
Also, in Edge, there is that _one_ pixel on the top which you could use to drag the whole window around. Using this .css this is not possible. Can this offset pixel be added as well?

**Comment by vovavili** [comment]
I managed to solve this by commenting out these two lines:

```
    .titlebar-buttonbox {
        z-index:3 !important;
    /*    padding-right:3px;   */
    }

    .titlebar-buttonbox * {
    /*    border-radius: 5px; */
        width:35px;
        height:38px;
    }
```

Should this behavior be default, or do you think the rounded aesthetic is preferred to common behavior Windows users would expect?

**Comment by ranmaru22** [comment]
To be honest, all the Windows stuff has been done by contributors because I neither use Windows nor do I have a machine to test that on, so I just trust you guys to know what's best there. 😀 

I'll take a look at the PR later and will merge it, if it fixes an annoyance for Windows users, no problem.
