### ISSUE TITLE
Sidebar stays open & Tabs collapse when hovering over a right click menu

### ISSUE THREAD

**Issue by Freeplayg** [ranmaru22/firefox-vertical-tabs#5]
Not sure if there's an easy fix for this

https://user-images.githubusercontent.com/40742947/125168521-ee463800-e173-11eb-8a6e-83ed5bba4ece.mp4

**Comment by ranmaru22** [comment]
I don't think there is, not without using JavaScript at least, unfortunately. 

The hover event just checks whether your pointer is over the bar, so unless there's some way to check in CSS if the context menu is open or not, there's little you can do.

**Comment by ranmaru22** [comment]
Thanks to @bmFtZQ this should be fixed now. Thanks, mate!
