### ISSUE TITLE
Closing a tab causes a scrollbar to show up for a short period of time.

### ISSUE THREAD

**Issue by XiCynx** [ranmaru22/firefox-vertical-tabs#58]
This vertical scrollbar shows up for about .25sec when you close out of a tab.
I'm sure this can be easily fixed by making sure scrollbars are hidden within that area, I am just too rusty in my css coding to figure out where it needs to go.

![image](https://user-images.githubusercontent.com/20632191/186549734-bb842883-8fbc-4c10-ad74-17d89bf5a02f.png)

**Comment by ranmaru22** [comment]
I can't reproduce this. Please provide more information (Firefox version, OS, etc.).

**Comment by XiCynx** [comment]
**Firefox version**
![image](https://user-images.githubusercontent.com/20632191/186791120-67906eba-0929-4efc-a7ed-d68ddbef609b.png)

**Windows System Info**
![image](https://user-images.githubusercontent.com/20632191/186791146-2b92b2d6-a0b2-4486-9a92-91e884b6f123.png)

**GIF recreating the issue**
![scrollbar](https://user-images.githubusercontent.com/20632191/186791243-8379df73-51df-4131-9305-0de0c67d2006.gif)

**Comment by Freeplayg** [comment]
Realized I'm actually experiencing this, too. It's just not as noticeable for me because of the collapsed scrollbar in Gnome linux. (notice the flashing line on the right side)

https://user-images.githubusercontent.com/40742947/186825736-2e80fbf5-67c0-4884-b4ac-9673518d731a.mp4
