### ISSUE TITLE
Smaller Close Clickspot 

### ISSUE THREAD

**Issue by TooSpooky** [ranmaru22/firefox-vertical-tabs#71]
Hello,

Would it be possible to shrink the click spot for closing a tab?

Loving the .css, it mimics another browser I prefer to use and allows me to happily use firefox as well. Although the click spots are a tad big.

Something along the lines of this or this size would be nice if possible
<img width="22" alt="BonBon_dJOMuosOdD" src="https://user-images.githubusercontent.com/21211292/193200219-3b764023-3b02-4378-8e02-52745503fb24.png">

Thanks and take care!

**Comment by ranmaru22** [comment]
Hi. Sure you can do that by changing the CSS. I won't make that the default, however, because a) the design is pretty much meant to mimic Edge's style, and b) I like the big ones. ;)

But feel free to fork and adjust to your liking.

**Comment by TooSpooky** [comment]
Haha, sounds goods. Thanks. 

Time to look around the CSS.
