### ISSUE TITLE
default-profile folder instead of profile folder on Readme

### ISSUE THREAD

**Issue by Jaimer** [ranmaru22/firefox-vertical-tabs#74]
I want to confirm that it works on Windows 11 with Firefox 106.0.1:

![imagen](https://user-images.githubusercontent.com/447088/197827922-ac7ef5b7-5079-4f1b-9283-3a48ff5ee717.png)

Just a little issue with the readme is that I had to create the chrome folder on the **default-release** profile and not on the **default** profile to work, maybe this is only on Windows.

![imagen](https://user-images.githubusercontent.com/447088/197826991-8f8e7571-9a08-437f-acb3-ba45138db84c.png)

**Comment by ranmaru22** [comment]
Hi, this depends on the version of Firefox you're using. I have to admit that I also don't fully understand which profile is for which, but if you have, say, a developer edition, a normal edition, and a beta channel installed, those will all use different profiles, with the `default` one being the fallback, if I understand correctly.

It's a bit confusing, yes, so sometimes you just have to play around and see which one to use so the changes show up. ;)
