### ISSUE TITLE
Tabs are much larger incorrectly

### ISSUE THREAD

**Issue by YidaozhanYa** [ranmaru22/firefox-vertical-tabs#80]
Before https://github.com/ranmaru22/firefox-vertical-tabs/commit/61c0731a10046d56238893716c347f6e2b4f8825
![图片](https://user-images.githubusercontent.com/73830635/202855994-609d7611-7fde-4f8f-b5f9-8d131e58d90f.png)

After https://github.com/ranmaru22/firefox-vertical-tabs/commit/61c0731a10046d56238893716c347f6e2b4f8825
![图片](https://user-images.githubusercontent.com/73830635/202856015-c9b9ec3a-abab-456d-92da-231fa5b45d47.png)
![图片](https://user-images.githubusercontent.com/73830635/202856018-221cd9fa-9b18-4914-a8f5-1df2c023e8f2.png)

This commit caused the tags to have incorrect heights. I am on Linux.

**Comment by bmFtZQ** [comment]
Try enabling compact mode in the extension settings:

![compact mode](https://user-images.githubusercontent.com/62812711/202881082-3ddff638-d455-4bba-9b88-ff1a64c96af6.png)

You probably had dynamic mode on before (which changes the height of the tabs depending on how much space is available), which didn't work properly with this theme, before and after that commit.
