### ISSUE TITLE
disable the reordering of pinned tabs when using tst

### ISSUE THREAD

**Issue by eskoONE** [ranmaru22/firefox-vertical-tabs#93]
[Imgur](https://i.imgur.com/vrx7wU3.gifv)

how can i make the pinned tabs not collapse like that and instead just get cut off? i had this working before but latest firefox broke something so i had to find another vertical tab css that works.

**Comment by ranmaru22** [comment]
Make sure you're using the latest version. This was addressed by @Freeplayg in #90 just recently.

**Comment by eskoONE** [comment]
i am, now was, using tree style tab instead of tabcenter and wanted a solution for that. but i switched to tabcenter for the time being because i cant work with the way the tst is behaving with this chrome.css.

ty for you help.

**Comment by ranmaru22** [comment]
Ah, I see. This mod is developed specifically for Tab Center and that's really the only thing we fest it with. If you swap that out with anything else, you're on your own. ;) 

But if if worked until recently it might just be #90 that broke it for you.
